[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/GetIntouch.html"
  to = "/html/GetIntouch.html"
  status = 200

[[redirects]]
  from = "/SignUp.html"
  to = "/html/SignUp.html"
  status = 200

[[redirects]]
  from = "/Contact-us.html"
  to = "/html/Contact-us.html"
  status = 200

[[redirects]]
  from = "/News-letter-form.html"
  to = "/html/News-letter-form.html"
  status = 200

[[redirects]]
  from = "/payment.html"
  to = "/html/payment.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/html/index.html"
  status = 200

[headers]
  for = "/*"
    [headers.values]
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"

  for = "/css/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  for = "/src/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  for = "/public/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  for = "/data/*"
    [headers.values]
      Cache-Control = "public, max-age=3600"

